# ---- Build (Vite) ----
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_WALLETCONNECT_PROJECT_ID
ARG VITE_ALCHEMY_MAINNET_RPC_URL
ARG VITE_ALCHEMY_SEPOLIA_RPC_URL
ARG VITE_ETHERSCAN_API_KEY   # <-- ajouté
ARG VITE_PUBLIC_BASE_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID \
    VITE_ALCHEMY_MAINNET_RPC_URL=$VITE_ALCHEMY_MAINNET_RPC_URL \
    VITE_ALCHEMY_SEPOLIA_RPC_URL=$VITE_ALCHEMY_SEPOLIA_RPC_URL \
    VITE_ETHERSCAN_API_KEY=$VITE_ETHERSCAN_API_KEY \   
    VITE_PUBLIC_BASE_URL=$VITE_PUBLIC_BASE_URL

RUN npm run build

# ---- Runtime (Nginx) ----
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
